### ISSUE TITLE
Pitchdeck - https://pitch.threadr.ai/

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/threadr#33]
Need everyones feedback on the pitchdeck content please. After you have read the deck we should be evaluating it to make sure we have market fit, a unique value proposition and trying to understand and validate that our product fits into at least one of these categories:

* Urgency - the problem our product addresses is immediate and pressing for our target customers
* Underserved - the target market or customer segment feels that current solutions do not meet their needs
* Unworkable - the issue or problem is so significant that it makes current processes or solutions ineffective. This can relate to situations where the problem our product solves is causing significant inefficiencies or obstacles for our customers.
* Unavoidable - Is the problem tied to mandatory requirements or regulations that demand compliance, making a solution essential?

[Startup Secrets
](https://coda.io/d/Startup-Secrets-Sandbox_dqDyOX97fb9/Synopsis_su8g6)

Please comment here with any feedback.

✨ https://pitch.threadr.ai is now available

**Comment by mfreeman451** [comment]
I think our `Example Queries` are kind of weak and don't speak to the unique value prop that we have -- our ability to infer relationships, store them, and analyze them..

**Comment by shrutimantri** [comment]
The pitch looks great!! We have covered all the points.
However, I thinks the slides are pretty verbose (giving a feel its AI generated). The slide content can be more point-based like slides 7, or point + small explanation like slide 9. What say? The present slide content would be more of what we speak during the pitch (in case we present), while the slide's actual content being reduced to only point + 1 liner.

**Comment by mfreeman451** [comment]
Good advice, will try and condense it and add slide notes.

**Comment by shrutimantri** [comment]
A slide after "Example Queries" could be more of a chatbot where we can show the queries asked to the bot, and the response by the bot. For example,

What were the top 3 conversations of utmost importance over the last week?
> 1. Search system was down for an hour in **production** impacting all the customers. The revenue impact is still uncertain.
    2. We signed up with 3 new customers: ABC, DEF and XYZ. 
    3. One more...

Does Jason from Sales team know our Platform Engineer Mike?
> There has been no direct communication between them, neither have they been part of the same thread. Hence, it is unlikely they know each other.

How many PagerDuty alerts fired over the last month along with their teamwise split?
> There were 152 PagerDuty alerts in total that were fired. 
   Here is the split:
   Platform team : 67
   DevOps team: 29
   CustomerSupport team: 10
   ABC team: 46

**Comment by mfreeman451** [comment]
I think we need to add a slide in here that covers our Agenda (first slide):

- Team
- Business Overview
- Market Opportunity
- Value Proposition
- Go To Market Plan
- Business Model
- Financials

**Comment by rutvik110** [comment]
> I think we need to add a slide in here that covers our Agenda (first slide:
> 
> **Agenda**
> 
> * Team
> * Business Overview
> * Market Opportunity
> * Value Proposition
> * Go To Market Plan
> * Business Model
> * Financials
> 
> I'm going to also try and reshape/rework/remove/add slides to fit into this outline as well

Was just thinking abt a similar outline. Glad we already got it going.

**Comment by mfreeman451** [comment]
going to close this out, the pitch-deck is created, we will probably keep iterating on it for a long time.
